[WIP] Groups Support
gruijter/com.gruijter.zigbee2mqtt pull request #8
Opened 2023-10-13 11:08 UTC by stefanrenne

The current state of this PR is more like a proof of concept to prove that it is possible to support groups.
This is the first time I developed anything for Homey so I'm expecting a lot of feedback :)
Next to that this PR contains a lot of duplicated code
that all said:
It adds support for Zigbee2Mqtt groups, it adds capabilities based on the first device in the group
Lets define some next steps together and make this happen!

2023-10-14 06:15 UTC, Vitaliy-Yakovchuk commented
IMHO: extremely valuable addition

2023-10-14 06:15 UTC, Vitaliy-Yakovchuk commented
IMHO: extremely valuable addition

2023-10-14 08:21 UTC, gruijter commented
Nice! If you cleanup the code and replace the group device icon+image I will merge.

2023-10-14 08:21 UTC, gruijter requested changes
pls cleanup duplicate code and replace device image and icon

2023-10-14 08:31 UTC, stefanrenne commented
@gruijter 
- do you have a suggested approach for removing duplicated code?, just to make sure I'm not modifing your architecture filosophie
- do you know how I could fix the Advanced settings are not shown for group?

2023-10-14 08:31 UTC, stefanrenne commented
@gruijter 
- do you have a suggested approach for removing duplicated code?, just to make sure I'm not modifing your architecture filosophie
- do you know how I could fix the Advanced settings are not shown for group?

2023-10-14 08:31 UTC, stefanrenne commented
@gruijter 
- do you have a suggested approach for removing duplicated code?, just to make sure I'm not modifing your architecture filosophie
- do you know how I could fix the Advanced settings are not shown for group?

2023-10-15 14:52 UTC, merged

2023-10-15 14:57 UTC, stefanrenne commented
O haha I was still fixing the duplicated code 😅

2023-10-15 14:59 UTC, gruijter commented
I cannot test groups myself (since I dont have them). So is this PR publishable?